/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-11-09 04:14:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDate;

public final class application_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.LocalDate");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Loan Application Form</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\t<!--\r\n");
      out.write("\twrite the html code to accept laon info from user and send to placeloan servlet\r\n");
      out.write("-->\r\n");
      out.write("<body>\r\n");
      out.write("<div align=Center><h2>Loan Application</h2></div>\r\n");
      out.write("\r\n");
      out.write("<div align=left>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"placeloan\" method=\"post\" name=\"applier\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"loanName\">Loan Description</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"loanName\" name=\"loanName\" required >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"loanAmountRequested\">Required Loan Amount(INR) </label>\r\n");
      out.write("\t\t\t<input type=\"number\" step=\"any\" id=\"loanAmountRequested\" name=\"loanAmountRequested\" required>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"loanApplicationDate\">Loan Applied Date</label>\r\n");
      out.write("\t\t\t<input type=\"date\" id=\"loanApplicationDate\" name=\"loanApplicationDate\" readonly value=");
      out.print(LocalDate.now());
      out.write(">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div><label for=\"businessStructure\">Business Structure</label></div>\r\n");
      out.write("\t\t\t<input type=\"radio\" id=\"individual\" name=\"businessStructure\" value=\"individual\" required>\r\n");
      out.write("  \t\t\t<label for=\"individual\">Individual</label>\r\n");
      out.write("  \t\t\t<input type=\"radio\" id=\"organization\" name=\"businessStructure\" value=\"organisation\">\r\n");
      out.write("  \t\t\t<label for=\"organization\">Organization</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div><label for=\"billingIndicator\">Billing Indicator</label></div>\r\n");
      out.write("\t\t\t<input type=\"radio\" id=\"salaried\" name=\"billingIndicator\" value=\"salaried\" required>\r\n");
      out.write("  \t\t\t<label for=\"salaried\">Salaried</label>\r\n");
      out.write("  \t\t\t<input type=\"radio\" id=\"nonSalaried\" name=\"billingIndicator\" value=\"non-salaried\">\r\n");
      out.write("  \t\t\t<label for=\"nonSalaried\">Non-Salaried</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div><label for=\"taxIndicator\">Tax Indicator</label></div>\r\n");
      out.write("\t\t\t<input type=\"radio\" id=\"taxPayer\" name=\"taxIndicator\" value=\"tax-payer\" required>\r\n");
      out.write("  \t\t\t<label for=\"taxPayer\">Tax-Payer</label>\r\n");
      out.write("  \t\t\t<input type=\"radio\" id=\"nontaxPayer\" name=\"taxIndicator\" value=\"non-tax-payer\">\r\n");
      out.write("  \t\t\t<label for=\"nontaxPayer\">Non-Tax Payer</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"address\">Address</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"address\" name=\"address\" required>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"phone\">Contact No</label>\r\n");
      out.write("\t\t\t<input type=\"number\" id=\"phone\" name=\"phone\" required>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"email\">Email id</label>\r\n");
      out.write("\t\t\t<input type=\"email\" id=\"email\" name=\"email\" required>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div><input type=\"submit\" value=\"Apply Loan\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
